# Generated by Django 5.2.8 on 2025-11-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
